server:
  port: 8082

---
spring:


  messages:
    basename: i18m/messages

  datasource:
    username: ${DB_USERNAME_PROD}
    url: jdbc:postgresql://${DB_HOST}/liquorsgolden
    password: ${DB_PASSWORD}
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    flyway:
      baselineOnMigrate: true
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      schemas: public
      createSchemas: true
      locations: db/migration, db/specific/h2
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
  flyway:
    enabled: true

  springdoc:
    api-docs:
      enabled: 'true'
    swagger-ui:
      enabled: 'true'
      path: /doc/swagger-ui.html